# Worked on by Nabil Ettachfini and Alexander Hamlet
class userRecipe < ActiveRecord::Migration[5.0]
def change
  create_table: userRecipe do |t|
  t.refrence: recipe_id
  t.refrence: user_id
  t.string: name
  t.string: recipe_url
                            # the id is auto generated by ruby do not need to include it.
                            # link this with an html.erb and do something in the roots to link them.
  t.timestamps
    end
  end
end
 
